name: first

on: push

jobs:
  ubuntu:
    name: ubuntu Job
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date

  windows:
    name: windows Job
    runs-on: windows-latest
    steps:
      - name: Print date
        run: date

  macos:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Print date
        run: date

  depends:
    needs: [ubuntu,macos,windows]
    name: Fourth Job
    runs-on: windows-latest
    steps:
      - name: Print date
        run: date
